theme:
  name: material
site_name: Kor
site_url: https://hello-world-99.github.io/Korean/
nav:
    - Home: index.md
    - 한글 자모/Korean Alphabet: alphabet.md
    - Reading Rules: rRules.md
    - Grammar: grammar.md
    - Dictionary: dictionary.md