markdown_extensions:
  - attr_list
  - md_in_html
plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
         - skip-lightbox
       auto_caption: false
       caption_position: bottom
theme:
  name: material
site_name: Korean
site_url: https://hello-world-99.github.io/Korean/
nav:
    - Home: index.md
    - 한글 자모/Korean Alphabet: alphabet.md
    - Reading Rules: rRules.md
    - 'Grammar': 
        - '1': grammar.md
        - '2': grammar2.md
    - Dictionary: dictionary.md
